# Generated by Django 5.2.3 on 2025-07-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
    ]
