# Generated by Django 5.2.3 on 2025-07-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('hex_code', models.CharField(blank=True, help_text='Hex color code (e.g., #FF0000)', max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('construction', models.CharField(blank=True, max_length=255, null=True)),
                ('composition', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_in_hand', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in inches', max_digits=6, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in GSM', max_digits=6, null=True)),
                ('lead_time', models.IntegerField(blank=True, help_text='Lead time in days', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fabric_images/')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('unit', models.CharField(choices=[('MTR', 'Meter'), ('YRD', 'Yard'), ('KG', 'Kilogram'), ('LB', 'Pound')], default='MTR', max_length=10)),
                ('minimum_order_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('BUTTON', 'Button'), ('ZIPPER', 'Zipper'), ('THREAD', 'Thread'), ('LABEL', 'Label'), ('TRIM', 'Trim'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('finish', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('SET', 'Set'), ('PAIR', 'Pair'), ('MTR', 'Meter'), ('YRD', 'Yard'), ('KG', 'Kilogram'), ('GRAM', 'Gram')], default='PCS', max_length=10)),
                ('lead_time', models.IntegerField(blank=True, help_text='Lead time in days', null=True)),
                ('stock', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('minimum_order_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessory_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('po_quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.accessory')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
            ],
            options={
                'unique_together': {('accessory', 'color')},
            },
        ),
        migrations.CreateModel(
            name='FabricColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('po_quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
            ],
            options={
                'unique_together': {('fabric', 'color')},
            },
        ),
    ]
