# Generated by Django 5.2.3 on 2025-07-08 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_accessory_unit_price_fabric_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('accessory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.accessory')),
                ('fabric', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
