# Generated by Django 5.2.3 on 2025-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/'),
        ),
    ]
