# Generated by Django 5.2.3 on 2025-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_accessory_image_fabric_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
