# Generated by Django 5.2.3 on 2025-07-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_color_fabriccolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('po_quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.accessory')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
            ],
            options={
                'unique_together': {('accessory', 'color')},
            },
        ),
    ]
