# Generated by Django 5.2.3 on 2025-07-09 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=100, unique=True)),
                ('supplier', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('total_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Open', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FabricReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('grn_no', models.CharField(max_length=100, unique=True, verbose_name='GRN No')),
                ('po_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.fabricpo')),
            ],
        ),
        migrations.CreateModel(
            name='FabricReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=10)),
                ('damage_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.fabricreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='FabricPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.fabricpo')),
            ],
            options={
                'unique_together': {('po', 'fabric', 'color')},
            },
        ),
    ]
