# Generated by Django 5.2.3 on 2025-07-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('total_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Related order if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('grn_no', models.CharField(max_length=100, unique=True, verbose_name='GRN No')),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('po_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.accessorypo')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=10)),
                ('damage_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('rate_received', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.accessory')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.accessoryreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='FabricPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('total_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Related order if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='FabricReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('grn_no', models.CharField(max_length=100, unique=True, verbose_name='GRN No')),
                ('po_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.fabricpo')),
            ],
        ),
        migrations.CreateModel(
            name='FabricReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=10)),
                ('damage_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('rate_received', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.fabricreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.accessory')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.accessorypo')),
            ],
            options={
                'unique_together': {('po', 'accessory', 'color')},
            },
        ),
        migrations.CreateModel(
            name='FabricPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.fabricpo')),
            ],
            options={
                'unique_together': {('po', 'fabric', 'color')},
            },
        ),
    ]
