# Generated by Django 5.2.3 on 2025-07-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100, unique=True)),
                ('customer', models.CharField(max_length=255)),
                ('customer_po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
        ),
        migrations.CreateModel(
            name='BOMVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('style_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.stylevariant')),
            ],
        ),
        migrations.CreateModel(
            name='BOMFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=4, max_digits=10)),
                ('issued_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_items', to='orders.bomversion')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'unique_together': {('order', 'fabric', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BOMAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=4, max_digits=10)),
                ('issued_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.accessory')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessory_items', to='orders.bomversion')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'unique_together': {('order', 'accessory', 'version')},
            },
        ),
    ]
