# Generated by Django 5.2.3 on 2025-07-08 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_accessory'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=4, max_digits=10)),
                ('issued_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.accessory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'unique_together': {('order', 'accessory')},
            },
        ),
        migrations.CreateModel(
            name='BOMFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=4, max_digits=10)),
                ('issued_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'unique_together': {('order', 'fabric')},
            },
        ),
    ]
