# Generated by Django 5.2.3 on 2025-07-08 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_accessorycolor'),
        ('orders', '0002_bomaccessory_bomfabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'version_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bomaccessory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bomfabric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bomaccessory',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessory_items', to='orders.bomversion'),
        ),
        migrations.AddField(
            model_name='bomfabric',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_items', to='orders.bomversion'),
        ),
        migrations.AlterUniqueTogether(
            name='bomaccessory',
            unique_together={('order', 'accessory', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='bomfabric',
            unique_together={('order', 'fabric', 'version')},
        ),
    ]
