# Generated by Django 5.2.3 on 2025-07-08 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='style_images/')),
            ],
        ),
        migrations.CreateModel(
            name='StyleAccessoryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.accessory')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
            options={
                'unique_together': {('style', 'accessory')},
            },
        ),
        migrations.CreateModel(
            name='StyleFabricConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
            options={
                'unique_together': {('style', 'fabric')},
            },
        ),
    ]
