# Generated by Django 5.2.3 on 2025-07-09 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='style_images/')),
            ],
        ),
        migrations.CreateModel(
            name='StyleCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('total_fabric_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_accessory_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('margin_markup', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage margin/markup', max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount', max_digits=5)),
                ('landed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.currency')),
                ('style', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
        ),
        migrations.CreateModel(
            name='StyleAccessoryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.accessory')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
            options={
                'unique_together': {('style', 'accessory')},
            },
        ),
        migrations.CreateModel(
            name='StyleFabricConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.fabric')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
            options={
                'unique_together': {('style', 'fabric')},
            },
        ),
        migrations.CreateModel(
            name='StyleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.size')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
            options={
                'unique_together': {('style', 'size', 'color')},
            },
        ),
    ]
