# Generated by Django 5.2.3 on 2025-07-08 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fabric_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_accessory_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('margin_markup', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage margin/markup', max_digits=5)),
                ('style', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
        ),
    ]
