# Generated by Django 5.2.3 on 2025-07-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='associated_styles',
            field=models.ManyToManyField(blank=True, to='styles.style'),
        ),
    ]
