# Generated by Django 5.2.3 on 2025-07-08 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_accessorycolor'),
        ('styles', '0002_stylecosting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.size')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
            options={
                'unique_together': {('style', 'size', 'color')},
            },
        ),
    ]
