# Generated by Django 5.2.3 on 2025-07-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('styles', '0002_style_associated_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='colors',
            field=models.ManyToManyField(blank=True, to='masters.color'),
        ),
        migrations.AddField(
            model_name='style',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='styles.size'),
        ),
    ]
