# Generated by Django 5.2.3 on 2025-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0003_size_stylevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylecosting',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount', max_digits=5),
        ),
        migrations.AddField(
            model_name='stylecosting',
            name='landed_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stylecosting',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
